#!/usr/bin/env php
<?php declare(strict_types=1);

namespace App;

$base_path = realpath(__DIR__ . '/../..');
require_once $base_path . '/vendor/autoload.php';

use App\Command\HelloWorldCommand;
use Symfony\Component\Console\Application;

Store::initialState(new HelloWorld());

$console = new Application();
$console->add(new HelloWorldCommand());
$console->run();
