version: "3"
services:
  http:
    image: leocavalcante/dwoole:1.0-development
    volumes:
      - ./:/app/
    ports:
      - "${DOCKER_HTTP_PORT:-9501}:9501"
    environment:
      ENTRY_POINT_FILE: /app/http/server.php
